<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            ['nombre' => 'Melanie Del Carmen', 'apellido' => 'Abreu Rosario', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Leander Javier', 'apellido' => 'Ariza Torres', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ashanthy', 'apellido' => 'Ayala Duran', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Christopher Abraham', 'apellido' => 'Balza Torrealba', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Victoria Esther', 'apellido' => 'Concepción Polonia', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tiphany', 'apellido' => 'Cruz Rosario', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'José Carlo', 'apellido' => 'Diaz Castillo', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Benellys Elizabeth', 'apellido' => 'Duran Ovalles', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lesly Shanell', 'apellido' => 'Espinola Abreu', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ian Xavier', 'apellido' => 'García Reyes', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ryan Gabriel', 'apellido' => 'Gil Tapia', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Maria Isabel', 'apellido' => 'Gonzalez Mendoza', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Genesis', 'apellido' => 'Hernández Jiménez', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Edward Manuel', 'apellido' => 'Hernández Peña', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Edwin Moisés', 'apellido' => 'Hierro Suriel', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Daniel', 'apellido' => 'Langomas', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lorenny', 'apellido' => 'Méndez Amadis', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Alvin Jared', 'apellido' => 'Mercedes Delgado', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Arlette Gabriela', 'apellido' => 'Mora Lopez', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pedro Luis', 'apellido' => 'Morel De La Cruz', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Christopher Rafael', 'apellido' => 'Núñez Marte', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Daysi Lissette', 'apellido' => 'Oliver Gómez', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Freilyn', 'apellido' => 'Paulino López', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Eduardo José', 'apellido' => 'Pichardo Siri', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Salvador', 'apellido' => 'Polanco Santos', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Kendra Chanel', 'apellido' => 'Puello Soto', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jhon Erick', 'apellido' => 'Quezada Del Villar', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Widalmy Celeste', 'apellido' => 'Quiro Apolinario', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Esmeralda Maria', 'apellido' => 'Suarez Genao', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Willbert', 'apellido' => 'Suarez Genao', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Leiry Anibel', 'apellido' => 'Trinidad Muñoz', 'grade_id' => 2, 'section_id' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Eliana Nicole', 'apellido' => 'Acosta Garcia', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Karen', 'apellido' => 'Alcantara Dominguez', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lusmania', 'apellido' => 'Alcius Oretienne', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Genesis Maria', 'apellido' => 'Alejandro Santos', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jesly Michelle', 'apellido' => 'Angeles Ayala', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Hanyely Jareny', 'apellido' => 'Aracena Castillo', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Edilee Marcell', 'apellido' => 'Arias Valdez', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jarianny Nicole', 'apellido' => 'Betances Garcia', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Scarlet Michelle', 'apellido' => 'Brito Rodriguez', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Francelis Miguelina', 'apellido' => 'Campusano Polanco', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Anneirys Esther', 'apellido' => 'Capellan', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Masiel', 'apellido' => 'Castillo Joaquin', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Amaraly', 'apellido' => 'Castillo Reyes', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ronanyeli Altagracia', 'apellido' => 'Castillo Rosario', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Gerolin Camil', 'apellido' => 'Castillo Suarez', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Laisha', 'apellido' => 'Castro Acosta', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yuliette Maria', 'apellido' => 'Collado Peralta', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jean Carlos', 'apellido' => 'Compres Diaz', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yuliet Marie', 'apellido' => 'Compres Holguin', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Luis Alexander', 'apellido' => 'Concepcion Muñoz', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Isauri Del Carmen', 'apellido' => 'Concepcion Santos', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Judith Altagracia', 'apellido' => 'Concepcion Taveras', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Leidy', 'apellido' => 'Contreras De La Cruz', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Maria De Jesus', 'apellido' => 'Coste Marte', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Kirsy Chaira', 'apellido' => 'De La Cruz Marte', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jesmerlyn Altagracia', 'apellido' => 'De La Cruz Polanco', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Keylin Kristal', 'apellido' => 'De Leon Calderon', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yimbeily Enmanuel', 'apellido' => 'Del Rosario Soto', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Omali Maria', 'apellido' => 'Delgado Betances', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Eidann Jose', 'apellido' => 'Diaz Navarro', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Johanny', 'apellido' => 'Diaz Garcia', 'grade_id' => 2, 'section_id' => 2, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dihanell Esteban', 'apellido' => 'Cruz Hidalgo', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yasmin Aracelis', 'apellido' => 'Dilonex Villafaña', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Enmanuel', 'apellido' => 'Duarte Jose', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Marlin Mercedes', 'apellido' => 'Duran Jose', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Keila Danna', 'apellido' => 'Duran Liriano', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lyah', 'apellido' => 'Ero Rodriguez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Nashly Alexa', 'apellido' => 'Espinal Jimenez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Marianny Del Carmen', 'apellido' => 'Espino Santiago', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Roely Shanik', 'apellido' => 'Felipe Rodriguez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mariza Del Carmen', 'apellido' => 'Feliz Rodriguez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Alex Miguel', 'apellido' => 'Feliz Volquez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Genesis Lismairy', 'apellido' => 'Fernandez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yanerys Esther', 'apellido' => 'Fernandez Fabian', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Carlos Daniel', 'apellido' => 'Flores Guzman', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Josue Isaac', 'apellido' => 'Frias Pichardo', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Britany Michelle', 'apellido' => 'Garcia Perez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mary Alexandra', 'apellido' => 'Garcia Suarez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Shayli Daniela', 'apellido' => 'Gomez Marte', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Raymir Jomar', 'apellido' => 'Gomez Marte', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ensly Yissela', 'apellido' => 'Gonzalez Castillo', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Clary Mariel', 'apellido' => 'Gutierrez Placencia', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Stiven', 'apellido' => 'Henriquez Tejada', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yeison Abraham', 'apellido' => 'Hernandez Hernandez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Chrys Hayward', 'apellido' => 'Herrera Paulino', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Franchely Channel', 'apellido' => 'Jimenez Reyes', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jhonabel', 'apellido' => 'Jorge Napoleon', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Laicha Rachell', 'apellido' => 'Lantigua Castro', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jadiel Manuel', 'apellido' => 'Leonardo Roque', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Franklin Ariel', 'apellido' => 'Lopez Cruz', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Omayris Del Carmen', 'apellido' => 'Lopez Lopez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sebastian Rafael', 'apellido' => 'Lora De Jesus', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Eilyn Yanibel', 'apellido' => 'Veras Perez', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Anyeuris De Jesus', 'apellido' => 'Ynfante Diaz', 'grade_id' => 2, 'section_id' => 3, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jatniel Rene', 'apellido' => 'Lopez Rosario', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Angel Gabriel', 'apellido' => 'Lorenzo', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sharolyn', 'apellido' => 'Marte Rodriguez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Eliel De Jesus', 'apellido' => 'Marte Suarez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Amelia Josailin', 'apellido' => 'Martinez Fernandez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Elianny Maria', 'apellido' => 'Martinez Mayi', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Esmerolin', 'apellido' => 'Martinez Ortiz', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Brianna', 'apellido' => 'Medina Castillo', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Brailyn Abel', 'apellido' => 'Mella', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Genesis Lisbeth', 'apellido' => 'Mercedes Vargas', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Crismeyli Eileen', 'apellido' => 'Minaya Gomez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rodrigo Rafael', 'apellido' => 'Monzon Gomez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rosnelly Maria', 'apellido' => 'Morales Reyes', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Kajol Anjolie', 'apellido' => 'Nuñez Nuñez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Skarlen Maribel', 'apellido' => 'Nuñez Rosario', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yisanny Nicole', 'apellido' => 'Nuñez Sosa', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yenifer Maria', 'apellido' => 'Padilla De La Cruz', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ronaldo Isael', 'apellido' => 'Paulino Luis', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Edgard Sebastian', 'apellido' => 'Payano Hernandez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yosmeiry', 'apellido' => 'Peguero Mendez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jose Ventura', 'apellido' => 'Peña Ovalles', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yadhaira Nicole', 'apellido' => 'Pichardo Peña', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Samuel Marcelino', 'apellido' => 'Polanco Reinoso', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Melany De Jesus', 'apellido' => 'Polo Duran', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Winilson', 'apellido' => 'Prophete', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Engers Enrique', 'apellido' => 'Quezada Pimentel', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Johelvis Stiven', 'apellido' => 'Ramirez Acevedo', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jederson Rafael', 'apellido' => 'Ramirez Castillo', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Brehilin Yisel', 'apellido' => 'Reyes Alvarado', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Camila', 'apellido' => 'Reynoso Muñoz', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jose Isaury', 'apellido' => 'Rodriguez Estevez', 'grade_id' => 2, 'section_id' => 4, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ihanna Alejandra', 'apellido' => 'Diaz Vargas', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Wisleydy', 'apellido' => 'Rodriguez Perdomo', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Keylis Marie', 'apellido' => 'Rodriguez Sanchez', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Germahiony Lisbeth', 'apellido' => 'Rojas Evangelista', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yariel', 'apellido' => 'Romero Diaz', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Abyam', 'apellido' => 'Rosario', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Darleny Isabel', 'apellido' => 'Rosario Jimenez', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Josue', 'apellido' => 'Rosario Lantigua', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Josmeilin Yudileidy', 'apellido' => 'Rosario Paez', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Angel Gabriel', 'apellido' => 'Rosario Santos', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Keisy Anaily', 'apellido' => 'Rosario Tapia', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bradley Abismael', 'apellido' => 'Sanchez Villafaña', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Johan David', 'apellido' => 'Santiago Robles', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Emely', 'apellido' => 'Santos', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ashli Maria', 'apellido' => 'Santos Cruz', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Joseph Adriel', 'apellido' => 'Santos Grullon', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dalkirys', 'apellido' => 'Santos Rosario', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Danllelys Michelle', 'apellido' => 'Santos Rosario', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jose Angel', 'apellido' => 'Soto Guzman', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Isenylie', 'apellido' => 'Suceus Fils', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sol Smarlynne', 'apellido' => 'Suriel Alejo', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yameli Lissette', 'apellido' => 'Tavarez Acosta', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mariely Nicol', 'apellido' => 'Tejada Espinal', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Enyer', 'apellido' => 'Tejada Mota', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Leah Shanelle', 'apellido' => 'Tiburcio Tavarez', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Genesis', 'apellido' => 'Trinidad Osoria', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Amelia Isabel', 'apellido' => 'Valerio Garcia', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Axel', 'apellido' => 'Vargas Guerrero', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'David Antonio', 'apellido' => 'Veras Cabral', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Daniela Rachel', 'apellido' => 'Veras Guerrero', 'grade_id' => 2, 'section_id' => 5, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yelitza Aimar', 'apellido' => 'Bueno Infante', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jade Esmeralda', 'apellido' => 'Caba Capellan', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Alexa Nicol', 'apellido' => 'Caceres', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Moises Valentin', 'apellido' => 'Corcino Balcacer', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Diugel', 'apellido' => 'Coste Viñas', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Liha Marie', 'apellido' => 'De La Cruz Valerio', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Anyeli', 'apellido' => 'Dilone Liriano', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Geovanna Altagracia', 'apellido' => 'Dominguez Belen', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rinaldi', 'apellido' => 'Garcia Arias', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yessire', 'apellido' => 'Garcia Castillo', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Edward', 'apellido' => 'Gutierrez Valerio', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mairelis Lissette', 'apellido' => 'Hernandez Galan', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ismary Laura', 'apellido' => 'Hernandez Hernandez', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Stephanie Marie', 'apellido' => 'Jimenez Miranda', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Aneliz Maria', 'apellido' => 'Mejia Alberto', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lianett Marie', 'apellido' => 'Molina Ureña', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Haly Lucy', 'apellido' => 'Nuñez Espinosa', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Samaria Clariza', 'apellido' => 'Paredes De León', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jose Raul', 'apellido' => 'Polanco Contreras', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rosibel', 'apellido' => 'Rodriguez Roman', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Adrian', 'apellido' => 'Romano Perez', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jacelis Del Pilar', 'apellido' => 'Rosario De Leon', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sofhia Camil', 'apellido' => 'Rosario Gutierrez', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Kariel Nahomy', 'apellido' => 'Sanchez Monsanto', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dylan', 'apellido' => 'Sandoval Guzman', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mirialys Arlin', 'apellido' => 'Severino Peña', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Stheisy Jasmine', 'apellido' => 'Soto Rosario', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Yismeiry Altagracia', 'apellido' => 'Then Hernandez', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Emelyn Mercedes', 'apellido' => 'Tiburcio De La Cruz', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Gloribel Altagracia', 'apellido' => 'Veloz Ruiz', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Avril', 'apellido' => 'Viñas Roque', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Anibel', 'apellido' => 'Viñas Veloz', 'grade_id' => 3, 'section_id' => 6, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],


        ];

        DB::table('students')->insert($students);
    }
}
